### ISSUE TITLE
Paginate a nested presenter

### ISSUE THREAD

**Issue by raisonon** [AdditionApps/flexible-presenter#17]
Is it possible to paginate a nested presenter? Something like this:

```
        return [
            'snapshots' => SnapshotsPresenter::collection($this->resource->snapshots->paginate(8)),
        ];
```

I can add this and it works:

`'snapshots' => SnapshotsPresenter::collection(Snapshot::paginate(8))`

But what is best practice to get the related models to the parent? Thanks!

**Comment by raisonon** [comment]
I'm currently thinking the best approach is to add a macro to manage pagination for collections... Along the lines of this: https://gist.github.com/simonhamp/549e8821946e2c40a617c85d2cf5af5e

🤔

**Comment by fourstacks** [comment]
I think this might potentially be more of a problem with your use of Eloquent rather than the Flexible Presenter package per se.

In your first example here:

```
return [
    'snapshots' => SnapshotsPresenter::collection(
        $this->resource->snapshots->paginate(8)),
    ];
```

You are retrieving an eloquent collection of snapshots from your resource: `$this->resource->snapshots`.

I think what you probably want to do instead is get a query builder instance that you can call `paginate()` on: `$this->resource->snapshots()->paginate(8)`.

This is done by calling the relationship method itself `->snapshots()` rather than the 'magic' accessor `->snapshots` as in the example above.

Let me know if that solves things for you

**Comment by raisonon** [comment]
You are totally right. Thanks so much @fourstacks . How foolish of me!!

**Comment by fourstacks** [comment]
@raisonon No worries - glad you're back on track!
